menu:
    Blog: https://blog.perfectacle.com
    Archive: /
    Tags: /tags/
    GitHub: https://github.com/perfectacle

favicon: /logo.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018
